controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      shoulder_pan_joint:
        trajectory: 0.05
        goal: 0.02
      shoulder_lift_joint:
        trajectory: 0.05
        goal: 0.02
      elbow_joint:
        trajectory: 0.05
        goal: 0.02
      wrist_pitch_joint:
        trajectory: 0.05
        goal: 0.02
      wrist_roll_joint:
        trajectory: 0.05
        goal: 0.02
