controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_pitch_joint
        - wrist_roll_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 50.0
      action_monitor_rate: 20.0
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0
        joint1:
          trajectory: 0.05
          goal: 0.03
      allow_partial_joints_goal: false

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        -jaw_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 50.0
      action_monitor_rate: 20.0
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0
        joint1:
          trajectory: 0.05
          goal: 0.03
      allow_partial_joints_goal: false
