controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

gripper_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      -jaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
     jaw_joint:
        trajectory: 0.05
        goal: 0.02
